---
engines:
  eslint:
    enabled: true
    checks:
      comma-dangle:
        enabled: false
ratings:
  paths:
  - "**.inc"
  - "**.js"
  - "**.jsx"
  - "**.module"
  - "**.php"
  - "**.py"
  - "**.rb"
  - "**.sass"
  - "**.html"
exclude_paths:
- "gulpfile.js"
- "www/lib/**/*"
- "Prototype/**/*"
